import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Humsafar is configured for Android.');
    }
    // Replace these placeholders with values generated by:
    // flutterfire configure
    return const FirebaseOptions(
      apiKey: 'REPLACE_WITH_FIREBASE_API_KEY',
      appId: 'REPLACE_WITH_FIREBASE_APP_ID',
      messagingSenderId: 'REPLACE_WITH_FIREBASE_MESSAGING_SENDER_ID',
      projectId: 'REPLACE_WITH_FIREBASE_PROJECT_ID',
    );
  }
}
